### ISSUE TITLE
bazaar-dl-worker spawns on app exit using CPU cycles while not doing anything.

### ISSUE THREAD

**Issue by deaglenomics** [kolunmi/bazaar#237]
On Arch every time I exit bazaar it will launch 5 instances of bazaar-dl-worker which is mainly using up CPU cycles - ~33% cpu load. As far as I an see its not pulling anything from the web and there is nothing queued for download. I manually have to kill those processes to get the cpu usage down.

<img width="1323" height="810" alt="Image" src="https://github.com/user-attachments/assets/4740433e-7c9e-488a-9e97-9df98cba17a0" />

 OS Garuda Linux x86_64
├ Kernel Linux 6.16.1-2-cachyos-lto
├󰏖 Packages 1747 (pacman)[stable], 5 (flatpak)
├ Shell fish 4.0.2
└ Age 102 days

 DE KDE Plasma 6.4.4
├󰧨 Window Manager KWin (Wayland)
├󰧨 Login Manager sddm 0.21.0 (Wayland)
├󰉼 WM Theme CatppuccinMocha-Classic
├󰉼 Color Themes Mokka (Mokka) [Qt]
├󰀻 System Icons Tela-circle-dracula-dark [Qt]
├ System Fonts Inter (10pt) [Qt]
└ Terminal konsole 25.8.0

󰌢 PC Desktop
├󰻠 CPU AMD Ryzen 7 7800X3D (16) @ 5.05 GHz
├󰍛 GPU AMD Radeon RX 9070 XT [Discrete]
├󰍛 Vulkan 1.4.325 - radv [Mesa 25.3.0-devel (git-c11f47481a)]
└󰍹 Display(s) 2560x1440 @ 360 Hz in 27" [External] *
└󰍹 Display(s) 2560x1440 @ 165 Hz in 27" [External]

**Comment by kolunmi** [comment]
Thanks for the issue, I'm surprised it took this long for someone to report this. I'm currently looking into it

**Comment by Saltane** [comment]
Same issue. Landed with version `0.3.2`, was not present on `0.2.3`.

**Comment by kolunmi** [comment]
I believe I've fixed it here 220588e86e1d88c85b917428f8bb6be9bcb9d74c

**Comment by kolunmi** [comment]
@deaglenomics  https://github.com/kolunmi/bazaar/releases/tag/v0.4.0 lmk if it is fixed for you

**Comment by BigCojones** [comment]
This was hogging up 70-80% of my 4 cores yesterday running idle in the background. On a under a week old bazzite install.

Is it even supposed to be running in the background?

**Comment by deaglenomics** [comment]
@kolunmi Just checked it and yep that fixed it , closing the app does not spawn the dl workers. Cheers :)

**Comment by ngocphamm** [comment]
This is still happening to me on Ubuntu 25.04, Bazaar version `0.4.5`.

I closed the app but those processes remain.

<img width="1039" height="495" alt="Image" src="https://github.com/user-attachments/assets/93884f58-0477-413e-b4de-b674117bde3f" />

**Comment by kolunmi** [comment]
@ngocphamm if the main Bazaar process is still there, everything is working as intended. Use `<ctrl>q` to quit the entire application instead of just closing the window.

**Comment by ngocphamm** [comment]
@kolunmi I see. I could have sworn I tried `ctr - q` with the same result, but I just tried it again and it worked.
