### ISSUE TITLE
[BUG] Logged out from Flathub account after reboot

### ISSUE THREAD

**Issue by ExistingPerson08** [kolunmi/bazaar#872]
### Describe the bug

After rebooting computer, I am logget out from flathub account in Bazaar

### OS

Fedora Silverblue 43, Niri 25.11

### Version

~ ❯❯❯ rpm -qi bazaar ✘ 1
Name : bazaar
Version : 0.7.0
Release : 1.fc43
Architecture: x86_64
Install Date: st 31. prosince 2025, 12:10:49
Group : Unspecified
Size : 2556182
License : GPL-3.0-only
Signature :
RSA/SHA256, st 31. prosince 2025, 08:44:15, Key ID 16bc8535a444a78a
RSA/SHA256, st 31. prosince 2025, 08:44:15, Key ID 16bc8535a444a78a
Source RPM : bazaar-0.7.0-1.fc43.src.rpm
Build Date : st 31. prosince 2025, 08:43:35
Build Host : aws-x86-64-normalreserved-prod-00864897-20251231-073435
Vendor : Fedora Copr - user ublue-os
URL : https://github.com/kolunmi/bazaar
Summary : Flatpak-centric software center and app store
Description :
A new app store with a focus on discovering and installing
applications and add-ons from Flatpak remotes, particularly Flathub.
It emphasizes supporting the developers who make the Linux desktop possible.

### Configured Flatpak Remotes

flathub - system
flathub - user

**Comment by JustAdreamerFL** [comment]
me too, what can i do to help debug this? I am on CachyOS and Bazaar is installed as flatpak

**Comment by jfmongrain** [comment]
Can confirm that the connection to Flathub does not persist between reboots.
Bluefin.
I connect to the service with Github, if that makes any difference.

**Comment by chrislowles** [comment]
Was trying out Bazaar on a custom image and it came up as logged out.

**Comment by JStrategic** [comment]
Having the same issue on Fedora Workstation, Bazaar installed as a flatpak.

**Comment by eberhardweber** [comment]
Getting logged out on Bazzite too, with the preinstalled flatpak.

**Comment by Optekah** [comment]
Bazzite for me. Happens with both my Github account as well as my GNOME Gitlab account. Very frustrating :/

Edit: It's happening to me on Arch too. Bazaar is installed via the native package manager/archinstall.

**Comment by JustAdreamerFL** [comment]
In version: 0.8.0 (vcs=e20d8c7), I tried to log in again, then restarted, and I am amazed. I stayed logged in. It would be nice if someone would verify it on their system too.

Edit:
I tested it yet again and the issue is still there.

**Comment by Optekah** [comment]
So far, after switching from the native Arch package to the Fatpak version and updating to 0.8.1 (vcs=43ce9f7), this issue seems to have been solved, for me at least. I logged out and in of my desktop, then did a few system reboots. All is well on my end.

Arch
GNOME 50
Linux 7.0.10-arch1-1
Bazaar flatpak 0.8.1 (vcs=43ce9f7)

**Comment by ExistingPerson08** [comment]
Looks like its fixed now

**Comment by Optekah** [comment]
And I'm right back to where I was before. It worked for a day, and a few reboots, but alas I am logged out once again.

**Comment by JustAdreamerFL** [comment]
@Optekah exactly what happened to me

**Comment by valdotdev** [comment]
+1 Still getting logged out after a reboot (loggediin via GitHub).
EDIT: Just updated and login seems to persist, at least for now.
EDIT2: Yup, unfortunately got logged out again.
